### ISSUE TITLE
Use Cases for Interoperability 

### ISSUE THREAD

**Issue by marydwyer** [dfinity/wg-identity-authentication#12]
The working group proposed the following use cases to include in the [Interoperability Overview](https://github.com/dfinity/wg-identity-authentication/blob/main/topics/interoperability.md). 

Please make comments and add additional use cases before the next meeting. 

| Number  | Use Case |
| ------ | -------------------------------------------------------------------------------------------------------------------- |
| UC-1 | A user wants to use specific photos they stored on dapp A to build a photo book on dapp B, without granting dapp B control over their photos in dapp A. |
| UC-2 | A user continuously proves that they own an NFT in wallet A to dapp B in a privacy-preserving manner. |
| UC-3 | A user easily aggregates their assets across multiple wallets in a privacy-preserving manner. |
| UC-4 | A user may use a single wallet across many dapps in a privacy-preserving manner. |

**Comment by frederikrothenberger** [comment]
I think, we should add #13 to the list here.
