### ISSUE TITLE
Transaction approval for proxying calls to other canisters

### ISSUE THREAD

**Issue by dostro** [dfinity/wg-identity-authentication#15]
Problem:
Developers may want to call other canisters as the authenticated user, but don't have a way of doing that when using an identity provider that generates new principals for each domain.

Requirements:
- Developers should request approval to call methods in other canisters
- Identity provider should protect users from malicious calls (i.e. pretend like it's asking DSCVR for username information when in reality it asks to transfer all your assets to a predefined wallet address)

Thoughts on a solution:
@frederikrothenberger suggested a potential solution where, similar to `.well-known` for alternative origins, developers set up something like `.well-known/proxy` to expose metadata on trusted endpoints and their descriptions (with support for internationalization).

**Comment by frederikrothenberger** [comment]
Given the importance of this topic and the multiple different approaches being taken right now, I have taken the time to create #16. Hopefully it prompts a lively discussion on how to implement the user-facing consent flow and helps us agree on a common specification that works for all IDPs.

**Comment by frederikrothenberger** [comment]
@dostro: I'm closing this issue because I think it is sufficiently addressed with [ICRC-21](https://github.com/dfinity/wg-identity-authentication/blob/main/topics/consent-msg.md) and [ICRC-25](https://github.com/dfinity/wg-identity-authentication/pull/32).
Please let me know if you disagree.
