### ISSUE TITLE
Summarized Feedback for ICRC-21

### ISSUE THREAD

**Issue by frederikrothenberger** [dfinity/wg-identity-authentication#38]
Quick summary of the feedback received across different channels:

# General

* [x] Prefix all candid methods and types with `icrc21_`
  * addressed in #39 
* [x] Gradual roll-out support proposed in #36 
* [x] Introduce `icrc21_supported_standards` method for extensions to consent messages?
  * addressed in #40 

If anything is missing, please add a comment and I'll add it to the list.

**Comment by sea-snake** [comment]
Is it right to assume that ICRC canisters would return ICRC-21 in the supported standards call?

**Comment by sea-snake** [comment]
> @sea-snake: Which standards call are you referring to? I think we might need an `icrc21_supported_standards` method in order to have ICRC-21 be extensible...

I was thinking for example ICRC-1 and 7 but since ICRC-21 doesn't really extend those standards, it makes more sense to have a  `icrc21_supported_standards` indeed.

**Comment by frederikrothenberger** [comment]
@sea-snake: See #40

**Comment by frederikrothenberger** [comment]
Summary of decisions made in September 5 working group session.

* Agreement on all proposed changes
  * The changes have been merged into the draft.
